# Generated by Django 4.1.1 on 2022-09-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esReinversion', models.BooleanField(default=False)),
                ('plazo', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidadDiasHoraOperativa', models.IntegerField()),
                ('cantidadDiasHoraNoOperativa', models.IntegerField()),
                ('cantidadDiasHoraOperativaReinversion', models.IntegerField()),
                ('cantidadDiasHoraNoOperativaReinversion', models.IntegerField()),
                ('horaOperativa', models.TimeField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('plazo', models.IntegerField()),
                ('esReinversion', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='inversion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
    ]
