# Generated by Django 4.1.1 on 2022-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='esReinversion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='horaOperativa',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Inversion',
        ),
    ]
