# Generated by Django 4.1.1 on 2022-09-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_producto_esreinversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reinversion', models.BooleanField()),
                ('plazo', models.IntegerField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
