# Generated by Django 4.1.1 on 2022-09-11 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_producto_id_inversion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='horaCreacion',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
