# Generated by Django 4.1.1 on 2022-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_inversion_horacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='fechaCreacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='horaCreacion',
            field=models.TimeField(),
        ),
    ]
