# Generated by Django 4.1.1 on 2022-09-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_inversion_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversion',
            old_name='reinversion',
            new_name='enReinversion',
        ),
        migrations.RenameField(
            model_name='inversion',
            old_name='fecha_creacion',
            new_name='fechaCreacion',
        ),
    ]
