# Generated by Django 4.1.1 on 2022-09-12 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_reinversion_inversion_enreinversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='plazo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
